# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11_L7diRgbDaqCcdJqAcZMug92dms4usj
"""

import requests

url = 'https://viacep.com.br/ws/'
cep = '30140071'
formato = '/xml/'

r = requests.get(url + cep + formato)

if (r.status_code == 200):
 print()
 print('JSON : ', r.text)
 print()
else:
 print('Nao houve sucesso na requisicao.')

import requests
url = 'https://viacep.com.br/ws/'
ceps = ['30140071', '30140072', '30140073', '30140074' , '30140075']
formato = '/json/'

for cep in ceps:

 r = requests.get(url + cep + formato)

 if (r.status_code == 200):
  print()
  print('JSON : ', r.text)
  print()
 else:
  print('Nao houve sucesso na requisicao.')

  print(cep)

import requests
url = 'https://viacep.com.br/abc/'
cep = '30140071'
formato = '/json/'

r = requests.get(url + cep + formato)

if (r.status_code == 200):
  print()
  print('JSON : ', r.text())
  print()
else:
  print('Nao houve sucesso na requisicao.')

import requests

r = requests.get('http://www.google.com/search', params={'q':
'Protocolo HTTP'})

def salvar_arquivo_html(texto_html):
  arquivo = open('resultado_busca.html', 'w')
  arquivo.write(texto_html)
  arquivo.close()

if (r.status_code == 200):
 print()
 print('Retorno : ', r.text)
 print()
else:
 print('Nao houve sucesso na requisicao.')