# -*- coding: utf-8 -*-
"""exercicios-python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wc7I6a7ucZj2_oWcO2X63nRSmsoSBfLV

# Exercícios

1. Escreva um algoritmo que imprima na tela: Olá Mundo!
"""

print('Olá Mundo!')

"""2. Escreva um programa que imprima seu nome na tela."""

nome = "Gabrielle Freitas"

print(nome)

"""3. O que o código a seguir imprime?

```python
print("*\n**\n***\n****\n*****")
```
"""

print("*\n**\n***\n****\n*****")

"""4. O que aparece na janela do console, quando cada uma das instruções abaixo são executadas, para: x = 2 e y = 3? Execute cada uma das linhas abaixos e, se necessário, faça os devidos ajustes no código.
    1. *print(“x = ” + x);*
    2. *print(“O valor de x + x é ” + (x + x));*
    3. *print(“x = ”);*
    4. *print((x + y) + “ = “ + (y + x));*

"""

x = 2
y = 3

print(" x = ",x)

print("\n O valor de x + x é ", (x + x))

print("\n x = ")

print("\n",(x + y) , " = " , (y + x))

"""5. Escreva um algoritmo que imprima na tela a seguinte mensagem:

> A programação é aprendida escrevendo programas - 
> Brian Kernighan

"""

print("A programação é aprendida escrevendo programas - Brian Kernighan")

"""6. Crie um algoritmo que imprima o produto entre os números 25 e 27"""

soma = 25*27

print(soma)

"""7. Crie um algoritmo que imprima a média aritmética entre os números 4, 12, 15."""

soma = 4 + 12 + 15
media = soma /3

print(media)

"""8. Faça um programa que leia um número inteiro e mostre-o na tela da seguinte forma: 

> O número inteiro digitado foi 4.
"""

num = input("Digite um número: ")

print("\n O número inteiro digitado foi", num)

"""9. Faça um programa que leia e imprima dois números inteiros na tela."""

num1 = int(input("Digite o primeiro número: "))

num2 = int(input("Digite o segundo número: "))

print(num1)
    
print(num2)

"""10. Faça um programa que leia um número inteiro e imprima seu número sucessor e antecessor."""

print ("Digite um número: ")
x = int(input())
print (x-1 , x+1)

"""11. Faça um programa que leia o nome, endereço e telefone de um usuário e imprima na tela."""

print ("Preencha seus dados: ")
nome = input("Nome: ")
end = input("Endereço: ")
tel = input("Telefone: ")
print("Nome: ", nome,
"\nEndereço: ", end,
"\nTelefone: ", tel)

"""12. Faça um programa que leia e multiplique dois números inteiros."""

print ("Digite dois numeros: ")
x= int(input())
y= int(input())
print ("O produto de" , x , "e" , y , "é:" , x*y)

"""13. Faça um programa que leia um número real e imprima a terça parte deste número."""

print ("Digite um numero: ")
x= int(input())
print("A terça parte de seu numero é", x/3)

"""14. Faça um programa que leia dois números inteiros e imprima o dividendo, divisor, quociente e resto da divisão"""



"""15. Escreva um programa que solicite do usuário dois números, e imprima o resultado da soma, subtração, multiplicação e divisão."""

print ("Digite dois numeros: ")
x= int(input())
y= int(input())
print("Produto:", x*y)
print("Soma:", x+y)
print("Subtração:", x-y)
print("Divisão:", x/y)

"""16. Faça um programa que leia quatro números inteiros, calcule e mostre a soma desses números."""

print ("Digite quatro numeros: ")
x= int(input())
y= int(input())
z= int(input())
w= int(input())

print("Soma dos números: ", x+y+z+w)

"""17. Faça um programa que receba três notas, calcule e mostre a média aritmética."""

print ("Digite as notas: ")
x= int(input())
y= int(input())
z= int(input())
print("A média das notas é: ", (x+y+z)/3)

"""18. Faça um programa que receba três notas e seus respectivos pesos, calcule e mostre a média ponderada."""

print ("Digite a nota 1: ")
x= int(input())
print ("Digite seu peso: ")
xp= int(input())
print ("Digite a nota 2: ")
y= int(input())
print ("Digite seu peso: ")
yp= int(input())
print ("Digite a nota 3: ")
z= int(input())
print ("Digite seu peso: ")
zp= int(input())

media=(x*xp + y*yp + z*zp)/(xp+yp+zp)

print("Sua nota é ", media)

"""19. Faça um programa que receba o salário de um funcionário, calcule e mostre o novo salário, sabendo-se que este sofreu um aumento de 25%."""

print ("Digite seu salário: ")
x= int(input())
print ("Seu novo salario é ", x*1.25)

"""20. Faça um programa que receba o salário de um funcionário e o percentual de aumento, calcule e mostre o valor do aumento e o novo salário. """

print ("Digite seu salario: ")
x= int(input())
print ("Digite seu aumento percentual: ")
y= int(input())
z= (x*(y/100))+x
print ("seu novo salario é ", z)

"""21.  Faça um programa que calcule e mostre a área de um triângulo. Sabe-se que: 
> Área = (base * altura) / 2.
"""

print ("Defina a base: ")
x= int(input())
print ("Defina a altura: ")
y= int(input())
z= (x*y)/2
print("Sua área é:" , z)

"""22. Escreva um programa que receba como entrada o raio de um círculo e imprima o diâmetro, a circunferência e a área. Para isso, utilize as fórmulas: diâmetro = 2r; circunferência = 2πr, área = πr²."""

import math

print("Digite o raio: ")
r= int(input())
d=r*2
c=2*math.pi*r
a=math.pi*(r**2)
print("O diametro é ", d)
print("A circunferencia é ", c)
print("A area é ", a)

"""23. Faça um programa que receba um número positivo e maior que zero, calcule e mostre:
    1. o número digitado ao quadrado;
    2. o número digitado ao cubo;
    3. a raiz quadrada do número digitado.
"""

import math

print("Digite o número: ")
x= int(input())
y=x**2
z=x**3
w=math.sqrt(x)
print ("O valor ao quadrado é ", y)
print ("O valor ao cubo é ", z)
print ("A raiz do valor é ", w)

"""24. Faça um programa que receba dois números maiores que zero, calcule e mostre um elevado ao outro."""

print("Digite o valor e sua potência: ")
x=int(input())
y=int(input())
print(x**y , y**x)

"""25. Sabe-se que: pé = 12 polegadas; 1 jarda = 3 pés e 1 milha = 1,760 jarda. Faça um programa que receba uma medida em pés, faça as conversões a seguir e mostre os resultados.
    1. polegadas;
    2. jardas;
    3. milhas.
"""

print ("Informe a medida em pés: ")
p=int(input())
pol=12*p
j=p/3
m=j/1.76
print(pol, j , m)

"""26. Escreva um programa que receba como entrada um número de 5 dígitos, separe o número em dígitos individuais e os imprima separados por 3 espaços cada um. Por exemplo, se o usuário digitar 42339, o programa deverá imprimir: 4    2    3    3.   Dica: utilize as operações de divisão e módulo para extrair cada dígito do número."""



"""27.  A nota final de um estudante é calculada a partir de três notas atribuídas, respectivamente, a um trabalho
de laboratório, a uma avaliação semestral e a um exame final. A média das três notas mencionadas
obedece aos pesos a seguir:

| Nota                    | Peso |
|-------------------------|------|
| Trabalho de Laboratório | 2    |
| Avaliação Semestral     | 3    |
| Exame Final             | 5    |


Faça um programa que receba as três notas, calcule e mostre a média ponderada e o conceito que segue
a tabela:

| Média Ponderada        | Conceito |
|------------------------|----------|
| 8,00 <= Média <= 10,00 | A        |
| 7,00 <= Média < 8,00   | B        |
| 6,00 <= Média < 7,00   | C        |
| 5,00 <= Média < 6,00   | D        |
| 0,00 <= Média < 5,00   | E        |
"""

print("Digite a nota de trabalho: ")
x=int(input())
tl=x*2
print("Digite a nota da avaliação: ")
y=int(input())
av=y*3
print("Digite a nota do exame final: ")
z=int(input())
ex=z*5

media=(tl+av+ex)/10

if  media >= 8:
  print("Sua média foi de ", media, "e conceito A")

elif media < 8 and media >= 7:
  print("Sua média foi de ", media, "e conceito B")

elif media < 7 and media >= 6:
  print("Sua média foi de ", media, "e conceito C")

elif media < 6 and media >= 5:
  print("Sua média foi de ", media, "e conceito D")

else:
  print("Sua média foi de ", media, "e conceito E")

"""28. Faça um programa que receba três notas de um aluno, calcule e mostre a média aritmética e a mensagem constante na tabela a seguir. 

| Média                  | Situação       |
|------------------------|----------------|
| 7,00 <= Média <= 10,00 | Aprovado       |
| 3,00 <= Média < 7,00   | Exame Especial |
| 0,00 <= Média < 3,00   | Reprovado      |
"""

print ("Digite as notas: ")
x= int(input())
y= int(input())
z= int(input())
media =(x+y+z)/3
print("sua média foi de " , media)

if  media >= 7:
  print("APROVADO")
elif media < 7 and media >= 3:
   print("exame especial")
else:
  print("REPORVADO")

"""29. Faça um programa para resolver equações do 2º grau.

$$
a^{2} + bx + c = 0
$$


Onde x é uma variável, sendo a, b e c constantes, com a ≠ 0 


$$
\Delta = b^{2} - 4ac
$$

$$
\Delta < 0 \rightarrow não \: existe  \: raiz  \: real
$$

$$
\Delta = 0 \rightarrow  existe  \: raiz  \: real
$$

$$
x = \frac{-b}{2a}
$$



$$
\Delta > 0 \rightarrow existem \: duas  \: raizes  \: reais
$$


$$
x_1 = \frac{-b \: + \: \sqrt{\Delta } }{2a}
$$

$$
x_2 = \frac{-b \: - \: \sqrt{\Delta } }{2a}
$$
"""

print("Defina os valores de A, B e C: ")
a=int(input())
b=int(input())
c=int(input())
delta = b**2-4*a*c

if delta == 0 :
  x= (b*-1)/2*a
  print("O valor de x é: ", x)

elif delta < 0 :
  print("Não existe raiz da equação")

else:
  xi = ((b*-1)+ delta)/2*a
  xii = ((b*-1)- delta)/2*a
  print ("Os valores da raiz são " , xi , xii)

"""30. Faça um programa que receba vários números, calcule e mostre:

    - A soma dos números digitados;
    - A quantidade de números digitados;
    - A média dos números digitados;
    - O maior número digitado;
    - O menor número digitado;
    - A média dos números pares;
    - A porcentagem dos números ímpares entre todos os números digitados.

Finalize a entrada de dados com a digitação do número 0.
"""

vet = []

num = ""

while(num != "0"):
  num = input("Digite um número: ")
  vet.append(int(num))

print(vet)

print(len(vet))
print(max(vet))
print(min(vet))
print(sum(vet))

"""31. Foi realizada uma pesquisa sobre algumas características físicas dos habitantes de uma região. Foram coletados os seguintes dados de cada habitante: sexo, cor dos olhos (A — azuis; ou C — castanhos), cor dos cabelos (L — louros; P — pretos; ou C — castanhos) e idade. Implemente os seguintes métodos:

    1. `leia_dados()`: leia esses dados, armazene e retorne os dados em uma lista;
    2. `media_idades(dados)`: calcula e retorne a média de idade das pessoas com olhos castanhos e cabelos pretos;
    3. `maior_idade(dados)`: determina e retorne a maior idade entre os habitantes;
    4. `frequencia_individuos(dados)`: calcula e retorna a quantidade de indivíduos do sexo feminino com idade entre 18 e 35 anos (inclusive) e que tenham olhos azuis e cabelos louros.
"""



"""32. Faça o método `analisa_numeros(numeros)` que receba uma lista de números como parâmetro, calcule e mostre:

    1. A Soma dos números;
    2. A quantidade de números;
    3. A média dos números;
    4. O maior número;
    5. O menor número;
    6. A média dos números pares;
    7. A porcentagem dos números ímpares entre todos os números da lista.
"""



"""33. Uma empresa quer transmitir dados pelo telefone, mas está preocupada com a interceptação telefônica. Todos os seus dados são transmitidos  como inteiros de quatro dígitos. Ela pediu para que você escreva um programa que criptografe seus dados, para que eles possam ser transmitidos com mais segurança. Implemente a função `criptogra(numero)` que receba como parâmetro um número inteiro de quatro dígitos e criptografe-o da seguinte forma: 

    * Substitua cada um dos dígitos do número usando a seguinte fórmula: `(digito +  7) módulo 10`; 
    * Após a substituição, troque o primeiro dígito pelo terceiro e troque o segundo dígito pelo quarto;
    * Retorne o número inteiro criptografado.
"""

